
@baseUrl = http://localhost:5000/api
@resourseName = branches

# Branches
# @name getAllBranches
GET {{baseUrl}}/{{resourseName}}?_page=1_limit=10

# Branch id
# @name getBranchById
GET {{baseUrl}}/{{resourseName}}/f09ec018-d46b-4c69-8d47-57b866a1cc14

# Branches
# @name getBranchesByBalance
GET {{baseUrl}}/{{resourseName}}?_page=1_limit=10balance_lte: 5000

###
# @name addBranch
POST {{baseUrl}}/{{resourseName}}
content-type: application/json

{
    "name": "HCM"
}

###

# @name updateBranch
PATCH {{baseUrl}}/{{resourseName}}/2
content-type: application/json

{
    "name": "HCM"
}

###
# @name deleteBranch
DELETE {{baseUrl}}/{{resourseName}}/6

# Transaction